# start from base
FROM ubuntu:18.04

# install system-wide deps for python and node
RUN apt-get -yqq update
RUN apt-get -yqq install python3-pip python3-dev gnupg libmysqlclient-dev 
RUN python3 -m pip install --upgrade pip setuptools wheel


# copy our application code
ADD search-service /opt/search-service 
WORKDIR /opt/search-service 

# fetch app specific deps
RUN pip3 install -r requirements.txt

# expose port
EXPOSE 9999

# start app
CMD [ "python3", "./search-service.py" ]
