# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serve_pb2 as serve__pb2


class serveServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.serve = channel.unary_unary(
                '/serveService/serve',
                request_serializer=serve__pb2.serveRequest.SerializeToString,
                response_deserializer=serve__pb2.serveResponse.FromString,
                )


class serveServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def serve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'serve': grpc.unary_unary_rpc_method_handler(
                    servicer.serve,
                    request_deserializer=serve__pb2.serveRequest.FromString,
                    response_serializer=serve__pb2.serveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class serveService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def serve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serveService/serve',
            serve__pb2.serveRequest.SerializeToString,
            serve__pb2.serveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
