# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serve.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bserve.proto\"\x1d\n\x0cserveRequest\x12\r\n\x05order\x18\x01 \x01(\t\"\x1f\n\rserveResponse\x12\x0e\n\x06status\x18\x04 \x01(\t28\n\x0cserveService\x12(\n\x05serve\x12\r.serveRequest\x1a\x0e.serveResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serve_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVEREQUEST._serialized_start=15
  _SERVEREQUEST._serialized_end=44
  _SERVERESPONSE._serialized_start=46
  _SERVERESPONSE._serialized_end=77
  _SERVESERVICE._serialized_start=79
  _SERVESERVICE._serialized_end=135
# @@protoc_insertion_point(module_scope)
