# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complete-order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omplete-order.proto\"%\n\x14\x63ompleteOrderRequest\x12\r\n\x05order\x18\x01 \x01(\t\"\'\n\x15\x63ompleteOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2X\n\x14\x63ompleteOrderService\x12@\n\rcompleteOrder\x12\x15.completeOrderRequest\x1a\x16.completeOrderResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complete_order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPLETEORDERREQUEST._serialized_start=24
  _COMPLETEORDERREQUEST._serialized_end=61
  _COMPLETEORDERRESPONSE._serialized_start=63
  _COMPLETEORDERRESPONSE._serialized_end=102
  _COMPLETEORDERSERVICE._serialized_start=104
  _COMPLETEORDERSERVICE._serialized_end=192
# @@protoc_insertion_point(module_scope)
