# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import complete_order_pb2 as complete__order__pb2


class completeOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.completeOrder = channel.unary_unary(
                '/completeOrderService/completeOrder',
                request_serializer=complete__order__pb2.completeOrderRequest.SerializeToString,
                response_deserializer=complete__order__pb2.completeOrderResponse.FromString,
                )


class completeOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def completeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_completeOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'completeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.completeOrder,
                    request_deserializer=complete__order__pb2.completeOrderRequest.FromString,
                    response_serializer=complete__order__pb2.completeOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'completeOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class completeOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def completeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/completeOrderService/completeOrder',
            complete__order__pb2.completeOrderRequest.SerializeToString,
            complete__order__pb2.completeOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
