# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"g\n\x0corderRequest\x12\x0e\n\x06sessId\x18\x01 \x01(\x03\x12\x11\n\ttruckname\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x14\n\x0corderDetails\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\"\x1f\n\rorderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t28\n\x0corderService\x12(\n\x05order\x12\r.orderRequest\x1a\x0e.orderResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERREQUEST._serialized_start=15
  _ORDERREQUEST._serialized_end=118
  _ORDERRESPONSE._serialized_start=120
  _ORDERRESPONSE._serialized_end=151
  _ORDERSERVICE._serialized_start=153
  _ORDERSERVICE._serialized_end=209
# @@protoc_insertion_point(module_scope)
