# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\"\x1c\n\rsearchRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"Z\n\x0esearchResponse\x12\x17\n\x06trucks\x18\x01 \x03(\x0b\x32\x07.Trucks\x12\x0c\n\x04hits\x18\x02 \x01(\x05\x12\x11\n\tlocations\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\".\n\x13searchStoreResponse\x12\x17\n\x06trucks\x18\x01 \x03(\x0b\x32\x07.Trucks\"V\n\x06Trucks\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfooditems\x18\x02 \x03(\t\x12\x1b\n\x08\x62ranches\x18\x03 \x03(\x0b\x32\t.Branches\x12\x0e\n\x06\x64rinks\x18\x04 \x01(\x08\"Y\n\x08\x42ranches\x12\r\n\x05hours\x18\x01 \x01(\t\x12\x10\n\x08schedule\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x1b\n\x08location\x18\x04 \x01(\x0b\x32\t.Location\"F\n\x08Location\x12\x11\n\tlongitude\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\t\x12\x15\n\rhuman_address\x18\x03 \x01(\t\"I\n\x0cHumanAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t2s\n\rsearchService\x12+\n\x06Search\x12\x0e.searchRequest\x1a\x0f.searchResponse\"\x00\x12\x35\n\x0bSearchStore\x12\x0e.searchRequest\x1a\x14.searchStoreResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHREQUEST._serialized_start=16
  _SEARCHREQUEST._serialized_end=44
  _SEARCHRESPONSE._serialized_start=46
  _SEARCHRESPONSE._serialized_end=136
  _SEARCHSTORERESPONSE._serialized_start=138
  _SEARCHSTORERESPONSE._serialized_end=184
  _TRUCKS._serialized_start=186
  _TRUCKS._serialized_end=272
  _BRANCHES._serialized_start=274
  _BRANCHES._serialized_end=363
  _LOCATION._serialized_start=365
  _LOCATION._serialized_end=435
  _HUMANADDRESS._serialized_start=437
  _HUMANADDRESS._serialized_end=510
  _SEARCHSERVICE._serialized_start=512
  _SEARCHSERVICE._serialized_end=627
# @@protoc_insertion_point(module_scope)
